version: "3"

services:
  clock:
    build: .
    volumes:
      - .:/app
      - ./backups:/root/backups/
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgres@database:5432/postgres
      - FREQUENCY=10.seconds

  database:
    image: postgres:9.4-alpine
